# Clean minimal starship config
# Format: [conda][py3.11][npm20] username@hostname: ~/path (branch)|✗ $

format = """$conda$python$nodejs$username$hostname$directory$git_branch$git_status $character"""

add_newline = false

# === ENVIRONMENT/VERSIONS (Blue square brackets) ===

# Conda environment
[conda]
format = '[\[${environment}\]]($style)[:](bright-black)'
style = "bold blue"
ignore_base = false

# Python version
[python]
format = '[\[py${version}\]]($style)'
version_format = "${major}.${minor}"
style = "bold blue"

# Node.js version
[nodejs]
format = '[\[npm${version}\]]($style)'
version_format = "${major}.${minor}"
style = "bold blue"

# === HOST/USER (Green with grey colon delimiter) ===

# Username
[username]
format = '[$user]($style)'
style_user = "bold green"
style_root = "bold red"
disabled = false
show_always = true

# Hostname with @ and grey colon
[hostname]
format = '[@$hostname]($style)[:](bright-black)'
style = "bold green"
ssh_only = false
disabled = false

# === PATH (Purple with grey colon delimiter) ===

# Directory
[directory]
format = '[$path]($style)'
style = "bold purple"
truncation_length = 8
truncation_symbol = "···/"
truncate_to_repo = true
repo_root_style = "bold italic purple"
home_symbol = "~"

# === GIT (Yellow parentheses for branch, | symbol only if status present) ===

# Git branch
[git_branch]
format = '[\(${branch}\)]($style)'
symbol = ""
style = "bold yellow"
truncation_length = 20

# Git status - pipe only shows if there's actual status
[git_status]
format = '([|$all_status$ahead_behind]($style))'
style = "bold yellow"
disabled = false
ahead = "↑${count}"
behind = "↓${count}"
diverged = "↕"
up_to_date = ""
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
deleted = "✗${count}"
conflicted = "≠${count}"
renamed = "»${count}"
stashed = "~${count}"

# === PROMPT CHARACTER ===

[character]
success_symbol = "[\\$](bold white)"
error_symbol = "[\\$](bold red)"
vicmd_symbol = "[◀](bold magenta)"

# === DISABLED MODULES ===

[aws]
disabled = true

[azure]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cmd_duration]
disabled = true

[docker_context]
disabled = true

[gcloud]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[kubernetes]
disabled = true

[memory_usage]
disabled = true

[nix_shell]
disabled = true

[package]
disabled = true

[rust]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[vagrant]
disabled = true