# Custom starship configuration matching your existing prompt style
# Save this as ~/.config/starship.toml

# Overall format - matches your current style: (conda_env):username@hostname:~/path:(git_branch)$
format = """$conda$python$nodejs:$username$hostname$directory$git_branch$git_status$character"""

# Disable the newline at the start
add_newline = false

# Conda environment
[conda]
format = "[\\((${environment})\\)]($style)"
style = "bold #6AA8D9"
ignore_base = false

# Python version
[python]
format = "[\\(py${version}\\)]($style)"
version_format = "${major}.${minor}"
style = "bold #5597CF"

# Node.js version
[nodejs]
format = "[\\(npm${version}\\)]($style)"
version_format = "${major}.${minor}"
style = "bold #2E78B8"

# Username - always show like your current prompt
[username]
style_user = "bold #7FB34D"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
show_always = true

# Hostname - show with @ like your current prompt
[hostname]
ssh_only = false
format = "[@$hostname]($style):"
style = "bold #7FB34D"
disabled = false

# Directory - smart truncation showing ~/...../dir1/dir2/current
[directory]
format = "[$path]($style):"
style = "bold #9966CC"
truncation_length = 8
truncation_symbol = "···/"
truncate_to_repo = true
repo_root_style = "bold italic #9966CC"
home_symbol = "~"

# Git branch - matches your :(branch) style
[git_branch]
format = "[\\((${branch}$git_status)\\)]($style)"
symbol = ""
style = "bold #DEA216"
truncation_length = 20

# Git status - minimal, only show if there are changes
[git_status]
format = "[\\($all_status\\)]($style)"
style = "italic #B8841A"
disabled = false
ahead = "↑${count}"
behind = "↓${count}"
diverged = "↕"
up_to_date = "✓"
untracked = "?${count}"
modified = "!${count}"
staged = "+${count}"
deleted = "✗${count}"
conflicted = "≠${count}"
renamed = "»${count}"
stashed = "~${count}"


# Prompt character - matches your $ style
[character]
success_symbol = "[\\$](bold #B5B5B5)"
error_symbol = "[\\$](bold #910000)"
vicmd_symbol = "[\\$](bold #B5B5B5)"



# Disable everything else to keep it clean
[aws]
disabled = true

[azure]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

[docker_context]
disabled = true

[package]
disabled = true

[terraform]
disabled = true

[vagrant]
disabled = true

[nix_shell]
disabled = true

[memory_usage]
disabled = true

[time]
disabled = true